In [1]:
import pandas as pd
import numpy as np

In [5]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [21,20,22]

})
df2 = pd.DataFrame({
    "Name": ["Zain", "Ayesha", "Hamza"],
    "Age": [22,25,26]
})

df1
df2
result = pd.concat([df1, df2])
result #they will concat vertically and the indexing followed according to hte
# both dataframes

     Name  Age
0     Ali   21
1    Sara   20
2   Ahmed   22
0    Zain   22
1  Ayesha   25
2   Hamza   26

In [6]:
# fix the indexing
result = pd.concat([df1, df2], ignore_index=True)
result

     Name  Age
0     Ali   21
1    Sara   20
2   Ahmed   22
3    Zain   22
4  Ayesha   25
5   Hamza   26

In [7]:
# concatinating more than two data frames
df3 = pd.DataFrame({
    "Name": ["Bilal", "Hina"],
    "Age": [25, 22]
})

reuslt = pd.concat([df1, df2, df3], ignore_index = True)
result

     Name  Age
0     Ali   21
1    Sara   20
2   Ahmed   22
3    Zain   22
4  Ayesha   25
5   Hamza   26

In [8]:
# different columns
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Age": [21, 20]
})
df2 = pd.DataFrame({
    "Name": ["Ahmed", "Zain"],
    "City": ["Lahore", "Islamabad"]
})

pd.concat([df1, df2], ignore_index=True )
# nice- jis table me available nahi ha wo col ki value waha jst NaN ajae ga

    Name   Age       City
0    Ali  21.0        NaN
1   Sara  20.0        NaN
2  Ahmed   NaN     Lahore
3   Zain   NaN  Islamabad

In [16]:
# Horizontal Concatination
# axis = 1  - join columns
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed"]
})
df2 = pd.DataFrame({
    "Age": [21, 20, 22]
})

# ab karte ha column wise concat
result = pd.concat([df1, df2], axis=1)
print(result)
#  axis = 0 row wise hoti ha concatination and axis = 1 col wise kar deta ha

    Name  Age
0    Ali   21
1   Sara   20
2  Ahmed   22

In [20]:
# horizontal concatination with different indexes
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed"]
}, index=[0,1,2])
df1

df2 = pd.DataFrame({
    "Age" :[21,20,22]
}, index=[1,2,3])
pd.concat([df1,df2], axis=1)

# horizontal concat aligns data using the index

    Name   Age
0    Ali   NaN
1   Sara  21.0
2  Ahmed  20.0
3    NaN  22.0

In [21]:
# join = "inner"
pd.concat(
    [df1, df2],
    axis = 1,
    join="inner"
)
# only index taht exist in both

    Name  Age
1   Sara   21
2  Ahmed   20

In [22]:
# join = "outer"
pd.concat([df1, df2], axis=1, join="outer")
# keeps everything
# missing values become NaN

    Name   Age
0    Ali   NaN
1   Sara  21.0
2  Ahmed  20.0
3    NaN  22.0

In [36]:
# keys
# this is useful when you want to remeber where each dataframa came from
result = pd.concat(
    [df1, df2],
    keys = ["First", "Second"]
)
result
# this creates a multiindex
result.loc["First"]

    Name  Age
0    Ali  NaN
1   Sara  NaN
2  Ahmed  NaN

In [ ]:
# pd concat vs merge
# concat - put these dataframes together
# merge - match rows based on a common key

# concat - stack data
# merge - match data

In [ ]:
# merging

In [63]:
# basic merging
students = pd.DataFrame({
    "student_id": [1,2,3,4],
    "Name": ["Ali", "Sara", "Ahmed", "Zain"],
    "dept_id": [10,20,10,30]
})

departments = pd.DataFrame({
    "dept_id": [10,20,30],
    "Department": [
        "SE",
        "CS",
        "EE"
    ]
})


result = pd.merge(students, departments, on="dept_id")
result

   student_id   Name  dept_id Department
0           1    Ali       10         SE
1           2   Sara       20         CS
2           3  Ahmed       10         SE
3           4   Zain       30         EE

In [ ]:
# on - tells pandas which colun should i use ot match teh dataframes

In [43]:
# inner join
pd.merge(students, departments,
         on="dept_id", how="inner")
# this is the default join
# it keeps only the matching rows

   student_id   Name  dept_id Department
0           1    Ali       10         SE
1           2   Sara       20         CS
2           3  Ahmed       10         SE
3           4   Zain       30         EE

In [44]:
# left join
pd.merge(
    students,
    departments,
    on='dept_id',
    how="left"
)

# keep everything from the left dataframe

   student_id   Name  dept_id Department
0           1    Ali       10         SE
1           2   Sara       20         CS
2           3  Ahmed       10         SE
3           4   Zain       30         EE

In [45]:
# right join
pd.merge(students, departments, on="dept_id", how="right")
# keeos everything from the right table

   student_id   Name  dept_id Department
0           1    Ali       10         SE
1           3  Ahmed       10         SE
2           2   Sara       20         CS
3           4   Zain       30         EE

In [46]:
# outer join
pd.merge(
    students,
    departments,
    on="dept_id",
    how="outer"
)
# keep everything from both datafarmes
# left + right
# unmatched values become NaN
# join types

   student_id   Name  dept_id Department
0           1    Ali       10         SE
1           3  Ahmed       10         SE
2           2   Sara       20         CS
3           4   Zain       30         EE

In [ ]:
# join types
# inner - matching rows only
# left - everything from left
# right  - everythign from right
# outer - everything from both

In [48]:
# different column names
students = pd.DataFrame({
    "student_id": [1,2,3],
    "Name": ["Ali", "Sara", "Ahmed"],
    "department_id": [10,20,10]
})

departments = pd.DataFrame({
    "dept_id": [10, 20],
    "Department": ["SE", "CS"]
})

pd.merge(
    students,
    departments,
    left_on="department_id",
    right_on="dept_id"
)
# means k left wale table me department id available ha and ye right wale me dept id

   student_id   Name  department_id  dept_id Department
0           1    Ali             10       10         SE
1           2   Sara             20       20         CS
2           3  Ahmed             10       10         SE

In [55]:
# multiple join columns
# someties one column isn't enough
sales = pd.DataFrame({
    "Store": ["A", "A", "B"],
    "Product":["Laptop", "Phone", "Laptop"],
    "Sales": [100,200,150]
})
prices = pd.DataFrame({
    "Store": ["A", "A", 'B'],
    "Product": ["Laptop", "Phone", "Laptop"],
    "Price": [1000,500, 900]
})

pd.merge(sales, prices, on="Store")
# we want store + product
pd.merge(sales, prices, on=["Store", "Product"])

  Store Product  Sales  Price
0     A  Laptop    100   1000
1     A   Phone    200    500
2     B  Laptop    150    900

In [60]:
# duplicate column names
print(pd.merge(sales, prices , on="Store"))
print("\n"*3)
pd.merge(sales, prices, on="Store", suffixes=("_sales", "_prices"))

  Store Product_x  Sales Product_y  Price
0     A    Laptop    100    Laptop   1000
1     A    Laptop    100     Phone    500
2     A     Phone    200    Laptop   1000
3     A     Phone    200     Phone    500
4     B    Laptop    150    Laptop    900

  Store Product_sales  Sales Product_prices  Price
0     A        Laptop    100         Laptop   1000
1     A        Laptop    100          Phone    500
2     A         Phone    200         Laptop   1000
3     A         Phone    200          Phone    500
4     B        Laptop    150         Laptop    900

In [61]:
# merge using index
pd.merge(
    df1,
    df2,
    left_index = True,
    right_index = True
)
# match the rows using their indexes

    Name  Age
1   Sara   21
2  Ahmed   20

In [64]:
# validate
# suppose you expect every student to mathc one department
pd.merge(
    students,
    departments,
    on="dept_id",
    validate="many_to_one"
)

   student_id   Name  dept_id Department
0           1    Ali       10         SE
1           2   Sara       20         CS
2           3  Ahmed       10         SE
3           4   Zain       30         EE

In [66]:
df = pd.read_csv("train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [69]:
# merge with titanic
passengers = df[["PassengerId", "Name", "Pclass"]]
passengers

fares = df[
    ["PassengerId", "Fare"]
]
fares

# merge both using the passenger id
pd.merge(passengers, fares, on="PassengerId")

,PassengerId,Name,Pclass,Fare
0,1,"Braund, Mr. Owen Harris",3,7.2500
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,71.2833
2,3,"Heikkinen, Miss. Laina",3,7.9250
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,53.1000
4,5,"Allen, Mr. William Henry",3,8.0500
...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,13.0000
887,888,"Graham, Miss. Margaret Edith",1,30.0000
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,23.4500
889,890,"Behr, Mr. Karl Howell",1,30.0000
890,891,"Dooley, Mr. Patrick",3,7.7500

In [78]:
passenger_info = df[["PassengerId", "Name", "Sex", "Pclass"]]
ticket_info = df[["PassengerId", "Fare", "Ticket"]]

# merge using passenger id
pd.merge(passenger_info, ticket_info, on="PassengerId")

# perfor an inner join
pd.merge(passenger_info, ticket_info, how="inner", on="PassengerId")
# perform a left join
pd.merge(passenger_info, ticket_info, how="left", on="PassengerId")

d =

,PassengerId,Name,Sex,Pclass,Fare,Ticket
0,1,"Braund, Mr. Owen Harris",male,3,7.2500,A/5 21171
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,71.2833,PC 17599
2,3,"Heikkinen, Miss. Laina",female,3,7.9250,STON/O2. 3101282
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,53.1000,113803
4,5,"Allen, Mr. William Henry",male,3,8.0500,373450
...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,2,13.0000,211536
887,888,"Graham, Miss. Margaret Edith",female,1,30.0000,112053
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,3,23.4500,W./C. 6607
889,890,"Behr, Mr. Karl Howell",male,1,30.0000,111369
890,891,"Dooley, Mr. Patrick",male,3,7.7500,370376