In [1]:
import pandas as pd
import numpy as np

In [3]:
# multiindexing allows pandas to use multiple levels of indexes instead of one

# it lets us represent higher dimensional/hierarchical data using lower dimensional
# pandas structures

In [12]:
# create a multiindex using from_tuples()

index = pd.MultiIndex.from_tuples([
    ("Islamabad", 2024),
    ("Islamabad", 2025),
    ("Lahore", 2024),
    ("Lahore", 2025)
])

# now create a series
sales=pd.Series(
    [100,150,200,250],
    index=index
)
sales
# sales.loc["Islamabad"]

Islamabad  2024    100
           2025    150
Lahore     2024    200
           2025    250
dtype: int64

In [20]:
# understanding the levels
print(sales.index)
print("\n"*2)
print(sales.index.names)
print("\n"*2)

# you can give names
sales.index.names = ["City", "Year"]
print(sales.index.names) #now the indexes has the names

print("\n"*3)
print(sales)

MultiIndex([('Islamabad', 2024),
            ('Islamabad', 2025),
            (   'Lahore', 2024),
            (   'Lahore', 2025)],
           names=['City', 'Year'])



['City', 'Year']



['City', 'Year']




City       Year
Islamabad  2024    100
           2025    150
Lahore     2024    200
           2025    250
dtype: int64

In [ ]:
# level 0 -> city
# level 1 -> year

In [21]:
# accessing multiindex Data
# this is where multiindex becomes useful
# get everything from isb
sales.loc["Islamabad"]

Year
2024    100
2025    150
dtype: int64

In [22]:
# get isb 2024
sales.loc["Islamabad", 2024]

np.int64(100)

In [23]:
# Partial Selection
# you dont have ot provide entry level
sales.loc["Lahore"]

Year
2024    200
2025    250
dtype: int64

In [25]:
# multiindex from product
# cartisian product kar deta ha product
pd.MultiIndex.from_product([
    ["Islamabad", "Lahore"],
    [2024,2025,2026]
])

MultiIndex([('Islamabad', 2024),
            ('Islamabad', 2025),
            ('Islamabad', 2026),
            (   'Lahore', 2024),
            (   'Lahore', 2025),
            (   'Lahore', 2026)],
           )

In [28]:
# multi index data frame
# multi index is not only for series
index = pd.MultiIndex.from_product([
    ["Islamabad", "Lahore"],
    [2024, 2025]
],
names=["City", "Year"])
df = pd.DataFrame(
    {
        "Sales": [100,150,200,250],
        "Profit": [20,30,40,50]
    },
    index=index
)
df

                Sales  Profit
City      Year
Islamabad 2024    100      20
          2025    150      30
Lahore    2024    200      40
          2025    250      50

In [31]:
# selecting from multiindex dataframe
df.loc["Islamabad"]


df.loc[("Islamabad", 2025)]

Sales     150
Profit     30
Name: (Islamabad, 2025), dtype: int64

In [32]:
df["Sales"]

City       Year
Islamabad  2024    100
           2025    150
Lahore     2024    200
           2025    250
Name: Sales, dtype: int64

In [34]:
df.loc["Islamabad", "Sales"]

Year
2024    100
2025    150
Name: Sales, dtype: int64

In [ ]:
# why not just keep city and year as normal columns
# You absolutely can.

# For example:

# City        Year       Sales
# Islamabad   2024       100
# Islamabad   2025       150
# Lahore      2024       200
# Lahore      2025       250

# That's often easier for beginners.

# MultiIndex becomes useful when your data naturally has hierarchical
#  relationships and you repeatedly need to select/aggregate by those levels.

In [45]:
# unstack
#index level column ban jata ha - most inner wala col ban jaye ga
print(df)
print("\n"*3)
print(df.unstack())
# ab yaha pe jo index wala yer tha wo ja k column ban gaya ha
print("\n"*3)
df2 = df.unstack()
df2.loc["Islamabad", "Sales"]

                Sales  Profit
City      Year
Islamabad 2024    100      20
          2025    150      30
Lahore    2024    200      40
          2025    250      50




          Sales      Profit
Year       2024 2025   2024 2025
City
Islamabad   100  150     20   30
Lahore      200  250     40   50

Year
2024    100
2025    150
Name: Islamabad, dtype: int64

In [53]:
# unstack with a specific level
sales
s2 = sales.unstack(level="Year")
# the year become the columns
s2.loc["Islamabad"]
s2.loc["Islamabad", 2024]

np.int64(100)

In [59]:
# stack - opposite of the unstack
# in it the column become the index
print("DF\n",df,"\n\n")
print("df.stack()\n",df.stack(),"\n\n")

DF
                 Sales  Profit
City      Year
Islamabad 2024    100      20
          2025    150      30
Lahore    2024    200      40
          2025    250      50


df.stack()
 City       Year
Islamabad  2024  Sales     100
                 Profit     20
           2025  Sales     150
                 Profit     30
Lahore     2024  Sales     200
                 Profit     40
           2025  Sales     250
                 Profit     50
dtype: int64

In [ ]:
# unstack → index → columns

# stack → columns → index
#
# Stack = stack columns down into the index. -- wider

# Unstack = pull an index level out into columns. -- longer

In [ ]:
# Why do we care about Long vs Wide?

# Different operations prefer different formats.

# Long format

# Excellent for:

# analysis
# grouping
# plotting
# statistical work
# Wide format

# Often easier for:

# reports
# presentations
# human reading

# You'll constantly convert between them.

In [65]:
# melt convert wide to long
df2 = pd.DataFrame({
    "Name": ["Ali", "Zarak"],
    "Maths": [90, 100],
    "English":[100,100],
    "Science": [56,100]
})
df2 #this is a wide data
# now lets use the melt on it to  convert it to long
long_df2 = df2.melt(id_vars="Name")
long_df2

    Name variable  value
0    Ali    Maths     90
1  Zarak    Maths    100
2    Ali  English    100
3  Zarak  English    100
4    Ali  Science     56
5  Zarak  Science    100

In [68]:
# give a better column name
long_df2 = df2.melt(
    id_vars="Name",
    var_name="Subject",
    value_name="Marks"
)
long_df2

    Name  Subject  Marks
0    Ali    Maths     90
1  Zarak    Maths    100
2    Ali  English    100
3  Zarak  English    100
4    Ali  Science     56
5  Zarak  Science    100

In [73]:
# melt with mult columns
df = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Gender": ["Male", "Female"],
    "Math": [90,80],
    "English": [85,95]
})
df.melt(
    id_vars=["Name", "Gender"],
    var_name="Subject",
    value_name="Marks"
)

   Name  Gender  Subject  Marks
0   Ali    Male     Math     90
1  Sara  Female     Math     80
2   Ali    Male  English     85
3  Sara  Female  English     95

In [74]:
# pivot table
# a pivot table summarizes data across multiple categories
df = pd.read_csv("train.csv")

In [79]:
# average fare for each passenger class and gender
pd.pivot_table(
    df,
    values="Fare",
    index="Pclass",
    columns="Sex",
    aggfunc="mean"
)

Sex         female       male
Pclass
1       106.125798  67.226127
2        21.970121  19.741782
3        16.118810  12.661633

In [82]:
pd.pivot_table(
    df,
    values="Fare",
    index="Pclass",
    columns="Sex",
    aggfunc="count"
)

Sex     female  male
Pclass
1           94   122
2           76   108
3          144   347

In [83]:
# pivot table with multiple aggregations
pd.pivot_table(
    df,
    values="Fare",
    index="Pclass",
    columns="Sex",
    aggfunc=["mean", "max"]
)

              mean                  max
Sex         female       male    female      male
Pclass
1       106.125798  67.226127  512.3292  512.3292
2        21.970121  19.741782   65.0000   73.5000
3        16.118810  12.661633   69.5500   69.5500

In [84]:
# pivot table with multiple indexes
pd.pivot_table(
    df,
    values="Fare",
    index=["Pclass","Embarked"],
    columns="Sex",
    aggfunc="mean"
)

Sex                  female       male
Pclass Embarked
1      C         115.640309  93.536707
       Q          90.000000  90.000000
       S          99.026910  52.949947
2      C          25.268457  25.421250
       Q          12.350000  12.350000
       S          21.912687  19.232474
3      C          14.694926   9.352237
       Q          10.307833  11.924251
       S          18.670077  13.307149

In [85]:
# fill na
# pivot table can contain NaN
pd.pivot_table(
    df,
    values="Fare",
    index="Pclass",
    columns="Sex",
    aggfunc="mean",
    fill_value=0
)

Sex         female       male
Pclass
1       106.125798  67.226127
2        21.970121  19.741782
3        16.118810  12.661633

In [ ]:
# Pivot Table vs GroupBy

# This is another common confusion.

# GroupBy

# Best when you want to perform grouped calculations.

# df.groupby("Pclass")["Fare"].mean()
# Pivot Table

# Best when you want a table/matrix showing relationships between categories.

# pd.pivot_table(
#     df,
#     values="Fare",
#     index="Pclass",
#     columns="Sex",
#     aggfunc="mean"
# )

# Think:

# groupby
# → analysis

# pivot_table
# → summary table

In [87]:
# titanic example - survival
# what percentage of passenger survide by class and gender
pd.pivot_table(
    df,
    values="Survived",
    index="Pclass",
    columns="Sex",
    aggfunc="mean"
) * 100

Sex        female       male
Pclass
1       96.808511  36.885246
2       92.105263  15.740741
3       50.000000  13.544669

In [91]:
# multi index + titanic group by
result = df.groupby(
    ["Pclass", "Sex"]
)["Fare"].mean()
result #gives a multiindex series

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [94]:
result.unstack()
# GroupBy → MultiIndex → Unstack

Sex         female       male
Pclass
1       106.125798  67.226127
2        21.970121  19.741782
3        16.118810  12.661633

In [96]:
# slicing multiindex
result = df.groupby(
    ["Pclass", "Sex"]
)["Fare"].mean()
result

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [99]:
# to get class 1
result.loc[1]

# to get 1 class and male
result.loc[(1,"male")]

np.float64(67.22612704918032)

In [100]:
# selecting multiple values
result.loc[
    [(1, "female"), (3, "male")]
]

Pclass  Sex
1       female    106.125798
3       male       12.661633
Name: Fare, dtype: float64

In [101]:
# xs - cross section
result.xs(1, level="Pclass")

Sex
female    106.125798
male       67.226127
Name: Fare, dtype: float64

In [102]:
result.index.names

FrozenList(['Pclass', 'Sex'])

In [107]:
# you can use the level name
result.xs("female", level="Sex")
# xs is a multiindex selection

Pclass
1    106.125798
2     21.970121
3     16.118810
Name: Fare, dtype: float64

In [108]:
# reseting multiindex
result

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [109]:
result.reset_index()

   Pclass     Sex        Fare
0       1  female  106.125798
1       1    male   67.226127
2       2  female   21.970121
3       2    male   19.741782
4       3  female   16.118810
5       3    male   12.661633

In [112]:
# multi index columns
tb = pd.pivot_table(
    df,
    values="Fare",
    index="Pclass",
    columns="Sex",
    aggfunc=["mean", "max"]
)
# That's a MultiIndex on the columns.

In [113]:
tb.columns

MultiIndex([('mean', 'female'),
            ('mean',   'male'),
            ( 'max', 'female'),
            ( 'max',   'male')],
           names=[None, 'Sex'])