In [1]:
import pandas as pd
import numpy as np

In [3]:
# from a list
marks = [90, 85, 70, 99]
s = pd.Series(marks)
print(s)
# index and values

0    90
1    85
2    70
3    99
dtype: int64

In [4]:
# from a tuple
marks = (10,20,30,40,50)
pd.Series(marks)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
# from a numpy array
arr = np.array([5,10,25,1,2,3])
pd.Series(arr)

0     5
1    10
2    25
3     1
4     2
5     3
dtype: int64

In [7]:
# from a dictionary
student = {
    "ali":90,
    "zarak":100,
    "alyia":100
}
s = pd.Series(student)
s
# it uses the keys as the index cz it can not be duplcate

ali       90
zarak    100
alyia    100
dtype: int64

In [9]:
# custom index
marks = [90,99,100]
students=["ali", "zarak", "salena"]
s = pd.Series(marks, index=students)
s

ali        90
zarak      99
salena    100
dtype: int64

In [10]:
# giving a name
s = pd.Series(
    [90,99,100],
    name="Marks"
)
print(s)

0     90
1     99
2    100
Name: Marks, dtype: int64

In [12]:
# read student-data.csv file
df = pd.read_csv("student-data.csv")
df
# this gives a datafram by default we have to squeeze true to make it series
# aha squeeze has been removed
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'passed'],
      dtype='object')

In [30]:
# reading only one column as series
schools = pd.read_csv("student-data.csv")["school"]
schools

0      GP
1      GP
2      GP
3      GP
4      GP
       ..
390    MS
391    MS
392    MS
393    MS
394    MS
Name: school, Length: 395, dtype: object

In [29]:
# series attributes
s = pd.Series(
    [90,85,60],
    index=["ali", "sara", "ahmen"],
    name="marks"
)
print("Size:", s.size)
print("Shape:",s.shape)
print("No of dimensions:",s.ndim)
print("Data Type:",s.dtype)
print("Name:",s.name)
print("Indexs:",s.index)
print("Values:",s.values)
print("Is Unique:",s.is_unique)
print("Has nans:",s.hasnans)

Size: 3
Shape: (3,)
No of dimensions: 1
Data Type: int64
Name: marks
Indexs: Index(['ali', 'sara', 'ahmen'], dtype='object')
Values: [90 85 60]
Is Unique: True
Has nans: False

In [34]:
# head
schools.head()
#
schools.head(2)

0    GP
1    GP
Name: school, dtype: object

In [36]:
# tail
schools.tail()
#
schools.tail(2)

393    MS
394    MS
Name: school, dtype: object

In [42]:
# sample() return random rows
schools.sample()
# default 1 sample ,, u can specify how much u want
schools.sample(4)

24     GP
158    GP
49     GP
225    GP
Name: school, dtype: object

In [43]:
# value counts
schools.value_counts() #how many times a value appeared

school
GP    349
MS     46
Name: count, dtype: int64

In [45]:

# sort values
# sort accorn to value
schools.sort_values()


# decending

schools.sort_values(ascending=False)

394    MS
360    MS
369    MS
368    MS
367    MS
       ..
129    GP
128    GP
127    GP
126    GP
197    GP
Name: school, Length: 395, dtype: object

In [48]:
# sort index
schools.sort_index()

# descending
schools.sort_index(ascending=False)

394    MS
393    MS
392    MS
391    MS
390    MS
       ..
4      GP
3      GP
2      GP
1      GP
0      GP
Name: school, Length: 395, dtype: object

In [49]:
# count
# counts non missing values
schools.count()

# it does not count None

np.int64(395)

In [50]:
# sum
schools.sum()
# output is funny here cz of our dataset
# lol

'GPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPGPMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMSMS'

In [53]:
# mean
s.mean()

np.float64(78.33333333333333)

In [54]:
# median
s.median()

85.0

In [55]:
# mode jo zyada bar appear huwa
s.mode() #sab aik bar appear hoe isi leye sab agaye

0    60
1    85
2    90
Name: marks, dtype: int64

In [56]:
# std
# standard deviation
s.std()
# Shows how spread out the values are.

16.072751268321593

In [57]:
# var - variance
s.var()

258.3333333333333

In [58]:
# min
s.min()

60

In [59]:
# max
s.max()

90

In [60]:
# describe -
s.describe()

count     3.000000
mean     78.333333
std      16.072751
min      60.000000
25%      72.500000
50%      85.000000
75%      87.500000
max      90.000000
Name: marks, dtype: float64

In [62]:
# indexing
s["ali"]

np.int64(90)

In [64]:
# slicing
s[1:3]

sara     85
ahmen    60
Name: marks, dtype: int64

In [65]:
# in the lbel the starta nd the end both are included
s["ali":"ahmen"]

ali      90
sara     85
ahmen    60
Name: marks, dtype: int64

In [72]:
# negative indexing
# idk its not working
s[-2:]

sara     85
ahmen    60
Name: marks, dtype: int64

In [73]:
# fancy indexing
s[[0,2]]

/tmp/ipykernel_973/613969936.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[0,2]]

ali      90
ahmen    60
Name: marks, dtype: int64

In [77]:
# boolean indexing
s[(s > 50) & (s < 80)]

ahmen    60
Name: marks, dtype: int64

In [91]:
# Question 1 – Student Marks Analysis
m = np.random.randint(40,100, 20)
students_name = ["ali", "zara", "ahmed", "fatima", "hassan", "ayesha", "umar", "sana", "hamza", "maryam", "bilal", "hira", "usman", "mehak", "rizwan", "naila", "asif", "sidra", "sajid", "kiran"]
s = pd.Series(m, index=students_name)
print("--Head:")
print(s.head())
print("--Tail:")
print(s.tail())
print("--Random:")
print(s.sample(4))
print("-- Sort by name")
print(s.sort_index())
print("-- Describe")
print(s.describe())
print('-- Student  who scored greater than 85')
print(s[s >= 85])
print("-- Student who scored between 70 and 90")
print(s[(s >= 70) & (s <= 90)])
print("-- Fancy indexing")
print(s[[1,2,3]])

--Head:
ali       61
zara      78
ahmed     90
fatima    66
hassan    65
dtype: int64
--Tail:
naila    73
asif     50
sidra    40
sajid    44
kiran    87
dtype: int64
--Random:
mehak    63
usman    51
hira     89
sana     89
dtype: int64
-- Sort by name
ahmed     90
ali       61
asif      50
ayesha    54
bilal     42
fatima    66
hamza     62
hassan    65
hira      89
kiran     87
maryam    87
mehak     63
naila     73
rizwan    63
sajid     44
sana      89
sidra     40
umar      95
usman     51
zara      78
dtype: int64
-- Describe
count    20.000000
mean     67.450000
std      17.664937
min      40.000000
25%      53.250000
50%      64.000000
75%      87.000000
max      95.000000
dtype: float64
-- Student  who scored greater than 85
ahmed     90
umar      95
sana      89
maryam    87
hira      89
kiran     87
dtype: int64
-- Student who scored between 70 and 90
zara      78
ahmed     90
sana      89
maryam    87
hira      89
naila     73
kiran     87
dtype: int64
-- Fancy indexing
zara      78
ahmed     90
fatima    66
dtype: int64

/tmp/ipykernel_973/1719803503.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[[1,2,3]])