In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [15]:
# the split apply combine concept
# data->split->apply->combine
df.groupby("Pclass")["Age"].mean()

df.head()
df.groupby("Ticket")["Name"].count()

Ticket
110152         3
110413         3
110465         2
110564         1
110813         1
              ..
W./C. 6608     4
W./C. 6609     1
W.E.P. 5734    1
W/C 14208      1
WE/P 5735      2
Name: Name, Length: 681, dtype: int64

In [18]:
df.groupby("Sex")
# pandas only creates group
# to actually see result
# you must perform an operation
df.groupby("Sex")["Age"].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [19]:
# sum
# total fare paid ny each class
df.groupby("Pclass")["Fare"].sum()

Pclass
1    18177.4125
2     3801.8417
3     6714.6951
Name: Fare, dtype: float64

In [20]:
# passenger in each class
df.groupby("Pclass")["PassengerId"].count()

Pclass
1    216
2    184
3    491
Name: PassengerId, dtype: int64

In [21]:
#
df.groupby("Pclass").size()

Pclass
1    216
2    184
3    491
dtype: int64

In [22]:
# min
df.groupby("Pclass")["Age"].min()

Pclass
1    0.92
2    0.67
3    0.42
Name: Age, dtype: float64

In [23]:
# max
df.groupby("Sex")["Age"].max()

Sex
female    63.0
male      80.0
Name: Age, dtype: float64

In [24]:
# median
df.groupby("Sex")["Fare"].median()

Sex
female    23.0
male      10.5
Name: Fare, dtype: float64

In [25]:
# multiple aggregations agg()
df.groupby("Sex")["Age"].agg(
    ["min", "max", "mean", "median"]
)

         min   max       mean  median
Sex
female  0.75  63.0  27.915709    27.0
male    0.42  80.0  30.726645    29.0

In [26]:
# different aggregation for different columns
df.groupby("Pclass").agg({
    "Age": "mean",
    "Fare": "sum"
})

              Age        Fare
Pclass
1       38.233441  18177.4125
2       29.877630   3801.8417
3       25.140620   6714.6951

In [29]:
# multiple functions
df.groupby("Pclass").agg({
    "Age": ["min", "median", "sum"],
    "Fare": ["min", "max", "mean"]
})

         Age                 Fare
         min median      sum  min       max       mean
Pclass
1       0.92   37.0  7111.42  0.0  512.3292  84.154687
2       0.67   29.0  5168.83  0.0   73.5000  20.662183
3       0.42   24.0  8924.92  0.0   69.5500  13.675550

In [30]:
# grouping by multiple columns
df.groupby(
    ["Sex", "Pclass"]
)["Age"].mean()
# male in each p class
# female in each p class

Sex     Pclass
female  1         34.611765
        2         28.722973
        3         21.750000
male    1         41.281386
        2         30.740707
        3         26.507589
Name: Age, dtype: float64

In [33]:
# get group
# we want only females
groups = df.groupby("Sex")
groups = groups.get_group("female")
groups.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [37]:
# iterating through groups
groups = df.groupby("Pclass")
for name, group in groups:
  print(name)
  print(group.head())

1
    PassengerId  Survived  Pclass  \
1             2         1       1
3             4         1       1
6             7         0       1
11           12         1       1
23           24         1       1

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
6                             McCarthy, Mr. Timothy J    male  54.0      0
11                           Bonnell, Miss. Elizabeth  female  58.0      0
23                       Sloper, Mr. William Thompson    male  28.0      0

    Parch    Ticket     Fare Cabin Embarked
1       0  PC 17599  71.2833   C85        C
3       0    113803  53.1000  C123        S
6       0     17463  51.8625   E46        S
11      0    113783  26.5500  C103        S
23      0    113788  35.5000    A6        S
2
    PassengerId  Survived  Pclass                                 Name  \
9            10         1       2  Nasser, Mrs. Nicholas (Adele Achem)
15           16         1       2     Hewlett, Mrs. (Mary D Kingcome)
17           18         1       2         Williams, Mr. Charles Eugene
20           21         0       2                 Fynney, Mr. Joseph J
21           22         1       2                Beesley, Mr. Lawrence

       Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
9   female  14.0      1      0  237736  30.0708   NaN        C
15  female  55.0      0      0  248706  16.0000   NaN        S
17    male   NaN      0      0  244373  13.0000   NaN        S
20    male  35.0      0      0  239865  26.0000   NaN        S
21    male  34.0      0      0  248698  13.0000   D56        S
3
   PassengerId  Survived  Pclass                            Name     Sex  \
0            1         0       3         Braund, Mr. Owen Harris    male
2            3         1       3          Heikkinen, Miss. Laina  female
4            5         0       3        Allen, Mr. William Henry    male
5            6         0       3                Moran, Mr. James    male
7            8         0       3  Palsson, Master. Gosta Leonard    male

    Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0  22.0      1      0         A/5 21171   7.2500   NaN        S
2  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
4  35.0      0      0            373450   8.0500   NaN        S
5   NaN      0      0            330877   8.4583   NaN        Q
7   2.0      3      1            349909  21.0750   NaN        S

In [38]:
# groupby on categorical columns
df.groupby("Sex").size()

Sex
female    314
male      577
dtype: int64

In [39]:
df.groupby("Embarked").size()

Embarked
C    168
Q     77
S    644
dtype: int64

In [43]:
df.groupby("Survived").size()

Survived
0    549
1    342
dtype: int64

In [44]:
# group by + value counts
df.groupby("Pclass")["Sex"].value_counts()

Pclass  Sex
1       male      122
        female     94
2       male      108
        female     76
3       male      347
        female    144
Name: count, dtype: int64

In [45]:
# group byand filtering
# average age
df.groupby("Sex")["Age"].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [46]:
df[df["Sex"] == "female"].groupby("Pclass")["Age"].mean()

Pclass
1    34.611765
2    28.722973
3    21.750000
Name: Age, dtype: float64

In [48]:
# as index
df.groupby("Pclass")["Fare"].mean()

# remain a normal column
df.groupby("Pclass",
           as_index=False)["Fare"].mean()
  # pclass wont beome the index

   Pclass       Fare
0       1  84.154687
1       2  20.662183
2       3  13.675550

In [50]:
# apply custom func to all
df.groupby("Pclass")["Fare"].apply(lambda x: x.max() - x.min())
# group banao p class ki base pe
# mean k split kar do pclass pe
# then select karo fare wala col
# then fare k har col se max - min nikalo
# end pe har aik pclass k leye fare ki value de do

Pclass
1    512.3292
2     73.5000
3     69.5500
Name: Fare, dtype: float64

In [53]:
df.groupby("Pclass")["Age"].apply(
    lambda x: x.isnull().sum()
)
# it counts missing ages in each class

Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

In [56]:
# transform
df["ClassAvgAge"] = df.groupby("Pclass")["Age"].transform("mean")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ClassAvgAge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,25.140620
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.233441
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,25.140620
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,38.233441
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,25.140620
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,29.877630
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,38.233441
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,25.140620
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,38.233441
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,25.140620

In [57]:
# question 1
df.groupby("Pclass")["Age"].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [58]:
# Find the average fare for males and females.
df.groupby("Sex")["Fare"].mean()

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

In [61]:
# Count passengers in each class using both count() and size().
df.groupby("Pclass").size()
df.groupby("Pclass")["PassengerId"].count()

Pclass
1    216
2    184
3    491
Name: PassengerId, dtype: int64

In [66]:
# Find the youngest and oldest passenger in each class
df.groupby("Sex")["Age"].max()
df.groupby("Sex")["Age"].min()

Sex
female    0.75
male      0.42
Name: Age, dtype: float64

In [71]:
# Find the median fare for each embarkation port.
df.groupby("Embarked")["Fare"].median()

Embarked
C    29.70
Q     7.75
S    13.00
Name: Fare, dtype: float64

In [73]:
# aggregation
df.groupby("Pclass")["Age"].agg(["max", "min", "mean", "median"])

         max   min       mean  median
Pclass
1       80.0  0.92  38.233441    37.0
2       70.0  0.67  29.877630    29.0
3       74.0  0.42  25.140620    24.0

In [74]:
df.groupby("Pclass").agg({
    "Age": ["mean"],
    "Fare":["count"]
})

              Age  Fare
             mean count
Pclass
1       38.233441   216
2       29.877630   184
3       25.140620   491

In [75]:
df.groupby(["Sex", "Fare"])["Fare"].mean()

Sex     Fare
female  6.7500        6.7500
        7.2250        7.2250
        7.2292        7.2292
        7.2500        7.2500
        7.4958        7.4958
                      ...
male    221.7792    221.7792
        227.5250    227.5250
        247.5208    247.5208
        263.0000    263.0000
        512.3292    512.3292
Name: Fare, Length: 349, dtype: float64

In [76]:
df.groupby("Pclass")["Survived"].sum()

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [82]:
# advanced group by
df.groupby(["Pclass", "Sex"])["Sex"].size()

Pclass  Sex
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: Sex, dtype: int64

In [83]:
df["FareRange"] = df.groupby("Pclass")["Fare"].apply(lambda x: x.max()- x.min())
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ClassAvgAge,FareRange
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,25.140620,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.233441,512.3292
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,25.140620,73.5000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,38.233441,69.5500
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,25.140620,NaN

In [86]:
df.groupby("Pclass")["Age"].value_counts()

Pclass  Age
1       35.0    9
        36.0    9
        24.0    7
        30.0    6
        38.0    6
               ..
3       61.0    1
        63.0    1
        65.0    1
        70.5    1
        74.0    1
Name: count, Length: 182, dtype: int64

In [87]:
df.groupby("Pclass")["Age"].apply(lambda x: x.isnull().sum())

Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

In [89]:
groups = df.groupby("Pclass")
groups.get_group(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ClassAvgAge,FareRange
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,29.87763,NaN
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,29.87763,NaN
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,29.87763,NaN
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S,29.87763,NaN
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S,29.87763,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C,29.87763,NaN
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,29.87763,NaN
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,29.87763,NaN
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,29.87763,NaN
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,29.87763,NaN